site_name: "Beach Tennis CoordiMate"

theme:
  #logo: assets/logo/logo.png
  #favicon: assets/logo/logo.png
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Início: index.md
  - Documentação:
    - Visão do produto e projeto:
      - Visão do Produto: doc-visao/1.visao-produto.md
      - Visão do Projeto: doc-visao/2.visao-projeto.md
      - Processo de Desenvolvimento: doc-visao/3.processo-dev.md
      - Processo de Engenharia de Requisitos: doc-visao/4.processo-requisitos.md
      - Lições Aprendidas: doc-visao/5.licoes-aprendidas.md
  - Sprints:
    - template:
      - Planning: sprints/template/planning.md
      - Review: sprints/template/review.md