site_name: "Beach Tennis CoordiMate"
repo_url: https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate
repo_name: BeachTennisCoordiMate
features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  #logo: assets/logo/logo.png
  #favicon: assets/logo/logo.png
  name: material
  language: pt-BR

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Início: index.md
  
  - Documentação:
    - Visão do produto e projeto:
      - Visão do Produto: doc-visao/1.visao-produto.md
      - Requisitos Funcionais e Não Funcionais: doc-visao/2.requisitos.md
      - Visão do Projeto: doc-visao/2.visao-projeto.md
      - Processo de Desenvolvimento: doc-visao/3.processo-dev.md
      - Processo de Engenharia de Requisitos: doc-visao/4.processo-requisitos.md
      - Lições Aprendidas: doc-visao/5.licoes-aprendidas.md
      
  - Sprints:
    - Sprint 0:
      - Planning: sprints/sprint0/planning.md
      - Review: sprints/sprint0/review.md
      
  - Entregas:
    - Unidade 1: entregas/1.entrega-unidade1.md

      
      
