site_name: "Beach Tennis CoordiMate"
repo_url: https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate
repo_name: BeachTennisCoordiMate
theme:
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo claro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo escuro
  #logo: assets/logo/logo.png
  #favicon: assets/logo/logo.png
  name: material
  language: pt-BR

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Início: index.md
  - Gamificação: gamificacao.md
  - Documentação:
    - Visão do produto e projeto:
      - Visão do Produto: doc-visao/1.visao-produto.md
      - Requisitos Funcionais e Não Funcionais: doc-visao/2.requisitos.md
      - Visão do Projeto: doc-visao/2.visao-projeto.md
      - Processo de Desenvolvimento: doc-visao/3.processo-dev.md
      - Processo de Engenharia de Requisitos: doc-visao/4.processo-requisitos.md
      - Lições Aprendidas: doc-visao/5.licoes-aprendidas.md
    - Backlog SAFE: backlog.md
    - MPV: mvp.md
  - Reuniões:
    - Pré-planejamento:
      - Reunião 01 - Documento de Visão: sprints/pre-planejamento/1.doc-visao.md
      - Sprint 06: sprints/pre-planejamento/sprint6.md
      - Sprint 09: sprints/pre-planejamento/sprint9.md
    - Scrum:
      - Sprint 10: sprints/scrum/sprint10.md
      
  - Entregas:
    - Unidade 1: entregas/1.entrega-unidade1.md
    - Unidade 2: entregas/2.entrega-unidade2.md

      
      
